"""empty message

Revision ID: a472887cdd13
Revises: 
Create Date: 2018-04-12 14:16:28.676071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a472887cdd13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('answeredDate', sa.DateTime(), nullable=False),
    sa.Column('day1a', sa.String(length=80), nullable=True),
    sa.Column('day1b', sa.String(length=80), nullable=True),
    sa.Column('day1c', sa.String(length=80), nullable=True),
    sa.Column('day2a', sa.String(length=80), nullable=True),
    sa.Column('day2b', sa.String(length=80), nullable=True),
    sa.Column('day2c', sa.String(length=80), nullable=True),
    sa.Column('day3a', sa.String(length=80), nullable=True),
    sa.Column('day3b', sa.String(length=80), nullable=True),
    sa.Column('day3c', sa.String(length=80), nullable=True),
    sa.Column('day4a', sa.String(length=80), nullable=True),
    sa.Column('day4b', sa.String(length=80), nullable=True),
    sa.Column('day4c', sa.String(length=80), nullable=True),
    sa.Column('day5a', sa.String(length=80), nullable=True),
    sa.Column('day5b', sa.String(length=80), nullable=True),
    sa.Column('day5c', sa.String(length=80), nullable=True),
    sa.Column('day6a', sa.String(length=80), nullable=True),
    sa.Column('day6b', sa.String(length=80), nullable=True),
    sa.Column('day6c', sa.String(length=80), nullable=True),
    sa.Column('day7a', sa.String(length=80), nullable=True),
    sa.Column('day7b', sa.String(length=80), nullable=True),
    sa.Column('day7c', sa.String(length=80), nullable=True),
    sa.Column('day8a', sa.String(length=80), nullable=True),
    sa.Column('day8b', sa.String(length=80), nullable=True),
    sa.Column('day8c', sa.String(length=80), nullable=True),
    sa.Column('day9a', sa.String(length=80), nullable=True),
    sa.Column('day9b', sa.String(length=80), nullable=True),
    sa.Column('day9c', sa.String(length=80), nullable=True),
    sa.Column('day10a', sa.String(length=80), nullable=True),
    sa.Column('day10b', sa.String(length=80), nullable=True),
    sa.Column('day10c', sa.String(length=80), nullable=True),
    sa.Column('day11a', sa.String(length=80), nullable=True),
    sa.Column('day11b', sa.String(length=80), nullable=True),
    sa.Column('day11c', sa.String(length=80), nullable=True),
    sa.Column('day12a', sa.String(length=80), nullable=True),
    sa.Column('day12b', sa.String(length=80), nullable=True),
    sa.Column('day12c', sa.String(length=80), nullable=True),
    sa.Column('day13a', sa.String(length=80), nullable=True),
    sa.Column('day13b', sa.String(length=80), nullable=True),
    sa.Column('day13c', sa.String(length=80), nullable=True),
    sa.Column('day14a', sa.String(length=80), nullable=True),
    sa.Column('day14b', sa.String(length=80), nullable=True),
    sa.Column('day14c', sa.String(length=80), nullable=True),
    sa.Column('q1', sa.Boolean(), nullable=True),
    sa.Column('q2', sa.Boolean(), nullable=True),
    sa.Column('q3', sa.Boolean(), nullable=True),
    sa.Column('q4', sa.Boolean(), nullable=True),
    sa.Column('q5', sa.Boolean(), nullable=True),
    sa.Column('q6', sa.Boolean(), nullable=True),
    sa.Column('q7', sa.Boolean(), nullable=True),
    sa.Column('q8', sa.Boolean(), nullable=True),
    sa.Column('q9', sa.Boolean(), nullable=True),
    sa.Column('q10', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar')
    op.drop_table('users')
    # ### end Alembic commands ###
